name: Crystal CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "*.md"
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "32 2 * * 2"

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec -Dpreview_mt --order random --error-on-warnings
#    - name: Run bulid
#      run: shards build -Dpreview_mt
    - name: Run format
      run: crystal tool format --check

